# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  typedoc:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
          registry-url: 'https://registry.npmjs.org'
      # Runs a single command using the runners shell
      - name: init
        run: npm i

      # Runs a set of commands using the runners shell
      - name: generate typedoc
        run: ls -l
      - name: generate typedoc
        run: npx typedoc --options tsdoc.json --out ./docs/type/ ./src/main.ts

      - name: Create new Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "github-actions@xpadev.net"
          git config user.name "github-actions"
          git checkout -b typedoc
          git add .
          git commit -m "auto generate"
          git push origin --delete typedoc
          git push origin typedoc